### ISSUE TITLE
SSKB Redirect heroku deploy

### ISSUE THREAD

**Issue by zikeron** [Sphinx-Society/kaizen-backend#94]
Redirect Heroku deploy
=

- [X] The issue is present in the latest release.
- [X] I have searched the [issues](https://github.com/Sphinx-Society/kaizen-backend) of this repository and believe that this is not a duplicate.

## Summary 💡

It's required the Deploy must be redirected to the properly Heroku project

## Requirements 🌈

These changes must be done carefully.

**Comment by AryRosvall** [comment]
Heroku is up!
